### ISSUE TITLE
Docs: Explain the interactions and rationale between opentelemetry and this project

### ISSUE THREAD

**Issue by ecourreges-orange** [spring-projects-experimental/spring-cloud-sleuth-otel#114]
The main readme of this project talks about integration with Opentelemetry, but to me, it lacks detail for the choice to be compelling:

- Does it use otel propagation instead of long time default of b3 in sleuth?
- How does it interact with opentelemetry-java-instrumentation or opentelemetry-java?
- In which case a developer would choose this project instead of just the otel agent?
  - only for migrating legacy spring projects already using sleuth?
  - because it's in between the agent approach of otel-java-instr and the manual approach of otel-java?
  - It uses less CPU or RAM?
  - ... 
- Is sleuth going to be deprecated?
- Why duplicate the effort of library instrumentation in brave?

I did a google search of opentelemetry vs spring-cloud-sleuth and it didn't lead to much, hence my issue.
This is at least a 5 day study for someone like me external to the project, but some of you may already have all the answers :wink:

Thanks,
Regards.

**Comment by marcingrzejszczak** [comment]
> Does it use otel propagation instead of long time default of b3 in sleuth?

OTel uses different modes of propagation (B3, OTLP, AWS) all depending on what you have all the classpath and what you set as properties - https://spring-projects-experimental.github.io/spring-cloud-sleuth-otel/docs/1.1.0-SNAPSHOT/reference/html/howto.html#how-to-change-context-propagation

> How does it interact with opentelemetry-java-instrumentation or opentelemetry-java?

Both JARs are being used by Spring Cloud Sleuth OTel. We are not instrumenting things via agent - we're just instrumenting Spring beans.

> In which case a developer would choose this project instead of just the otel agent? 

This project is using instrumentation that is compatible with other Spring projects. The Spring team knows how to work with Spring ;)

> Is sleuth going to be deprecated?

https://github.com/spring-cloud/spring-cloud-sleuth/tree/main#spring-cloud-sleuth - it's feature complete

> Why duplicate the effort of library instrumentation in brave?

Sometimes we're heavily influenced by what Brave does to create an abstraction in Sleuth. That way you can use any other Tracer e.g. OTel to have the same instrumentation. So you instrument once but you can use different tracers.
