### ISSUE TITLE
How to inject trace baggage/tags into MDC?

### ISSUE THREAD

**Issue by moreirajo** [spring-projects-experimental/spring-cloud-sleuth-otel#116]
Hi,

I have a spring boot app using [spring cloud sleuth otel](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel) version `1.1.0-M6` and I want to add the trace baggage to MDC so my logs (sl4j) can print that key. 
It is worth noting that my app is reactive (webflux).

I tried:
```java
@Autowired private org.springframework.cloud.sleuth.Tracer tracer;
...
tracer.createBaggage("my-key", "some-value");
```
application.yaml:
```yam
spring:
  sleuth:
    baggage:
      correlation-fields:
      - my-key
```

It works when I create the baggage for a couple of logs but then stop working.

Am I missing something?

**Comment by marcingrzejszczak** [comment]
Can you check the https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/baggage-producer and https://github.com/spring-cloud-samples/spring-cloud-sleuth-samples/tree/main/baggage-consumer for an example of how to pass baggage?
