### ISSUE TITLE
Spring Sleuth doesn't send all the traces to Jaeger

### ISSUE THREAD

**Issue by SimoneGiusso** [spring-projects-experimental/spring-cloud-sleuth-otel#117]
Hi,

this issue follow another issue already opened in the [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/6256) repo.

I was testing this `spring-cloud-sleuth-otel` project with a demo application using Jaeger as Collector. This demo application can be found in my [repo](https://github.com/SimoneGiusso/OpenTelemetryJaegerDemo) and it consists of a simple controller composed by just one endpoint to get a random number.

After I had run this application locally I tried to call the endpoint (with Postman). The application was run together with the All-in-One executable Jaeger service (by means of docker, see official [documentation](https://www.jaegertracing.io/docs/1.35/getting-started/#all-in-one)).

I noticed that some traces are not correctly exported. From this [log](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/files/9057198/OpenTelemetryJaegerDemo_Log.txt) you can see that I called the endpoint 6 times, however the trace seems to be exported only twice: the `LoggingSpanExporter` prints something when the trace is visible in the Jaeger GUI.

The `opentelemetry-java-instrumentation` team have excluded the possibility of jaeger or jaeger exporter losing things. 

All is running locally (Jaeger container + Demo APP with intellijIDEA) on my M1 Air mac.

**Comment by marcingrzejszczak** [comment]
Have you checked whether simply the traces were not sampled out?

**Comment by SimoneGiusso** [comment]
> Have you checked whether simply the traces were not sampled out?

How I suppose to check that? Actually I would expect to have all the traces sampled with the test I performed. From the official [spring-cloud-sleuth](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/appendix.html#appendix) I can see that `spring.sleuth.sampler.rate` has default value 10. If I didn't misinterpreted this parameter, it means that it should trace 10 traces per second. Since, as you can see from the log I shared, the endpoint was called 6 times in around 1 second, I would expect to have sampled out all the traces.

**Comment by marcingrzejszczak** [comment]
That's what I would expect too. Can you set `spring.sleuth.sampler.probability=1` and check again?

**Comment by SimoneGiusso** [comment]
> That's what I would expect too. Can you set `spring.sleuth.sampler.probability=1` and check again?

I updated the demo project and push a commit in my repo. Nothing has changed: I performed 10 requests and only 2 traces were sampled out.

**Comment by SimoneGiusso** [comment]
@switte-sf thanks a lot I missed this configuration. I confirm that it works. 

Just two considerations @marcingrzejszczak:

- Makes sense to have `1.0` has default value for this `spring.sleuth.otel.config.trace-id-ratio-based` instead of `0.1`? I think when a user start to "play" with this tracing tools (Sleuth + Otel + Jeager, etc...) he would expect to see all the traces no?
- Would make sense to have a small citation in the documentation regarding this configuration (in the [sampling](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-sampling) section)? Maybe the appendices section is not enough since it looks like an important setting to me.
