### ISSUE TITLE
Baggage is not propagated to MDC

### ISSUE THREAD

**Issue by Michal-Kucera** [spring-projects-experimental/spring-cloud-sleuth-otel#122]
**My setup**
Spring Boot: `2.7.2`
Spring Cloud: `2021.0.3`
Spring Cloud Sleuth OTEL: `1.1.0-M7`

**Describe the bug**
Baggage does not seem to be propagated to MDC in other threads when using Spring WebFlux. This looks to me like the old issue with [MDC and project Reactor](https://github.com/reactor/reactor-core/issues/1985), yet, I'd love to discuss this.

**Sample**
I've created a `WebFilter` which gets initialised right after `AuthenticationWebFilter`, it extracts `user ID` from `SecurityContext`, and adds it as a tag, as well as baggage to tracing context, see the following code:

```kotlin
import org.springframework.boot.web.reactive.filter.OrderedWebFilter
import org.springframework.cloud.sleuth.Tracer
import org.springframework.context.annotation.Configuration
import org.springframework.security.config.web.server.SecurityWebFiltersOrder.AUTHENTICATION
import org.springframework.security.core.context.ReactiveSecurityContextHolder
import org.springframework.web.server.ServerWebExchange
import org.springframework.web.server.WebFilterChain
import reactor.core.publisher.Mono

@Configuration
class UserIdWebFilter(
    private val tracer: Tracer
) : OrderedWebFilter {

    override fun getOrder() = AUTHENTICATION.order + 1

    override fun filter(
        exchange: ServerWebExchange,
        chain: WebFilterChain
    ): Mono<Void> = ReactiveSecurityContextHolder.getContext()
        .mapNotNull { it.authentication }
        .map { it.name }
        .doOnNext {
            tracer.currentSpanCustomizer()?.tag("userId", it)
            tracer.createBaggage("userId", it)
        }
        .then(chain.filter(exchange))
}
```

With the aforementioned, I can see `userId` tag in current spans, though, I'd also expect to be able to print `%X{userId:--}` in logs, via MDC.. yet, MDC works only in the current thread.

To prove MDC works only per thread, I've tried the following as a workaround, where I autowire `Tracer` in each controller, and re-add `userId` baggage, and it seems to be working:

```kotlin
import org.springframework.cloud.sleuth.Tracer
import org.springframework.http.ResponseEntity
import org.springframework.security.core.Authentication
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RestController

@RestController
class AccountController(private val tracer: Tracer) {

    @GetMapping("accounts")
    suspend fun getAccounts(
        authentication: Authentication
    ): ResponseEntity<AccountResponse> {
        tracer.createBaggage("userId", authentication.name)
        // .....
    }
}
```

Would you have any idea how to make this working, please?

**Comment by marcingrzejszczak** [comment]
Can you try using the Sleuth's `WebFluxSleuthOperators` where you can use `ServerWebExchange` to manually work with traces within the Reactor flow?

**Comment by Michal-Kucera** [comment]
Thanks for the tip @marcingrzejszczak, I've tried to wrap the entire filter as per snipped below, with no results. In my console I can still see that `user-id` is missing in reactor's threads. Perhaps you meant to do something different?

```kotlin
override fun filter(
    exchange: ServerWebExchange,
    chain: WebFilterChain
): Mono<Void> = WebFluxSleuthOperators.withSpanInScope(
    tracer,
    tracer.currentTraceContext(),
    exchange,
    Callable {
        ReactiveSecurityContextHolder.getContext()
            .mapNotNull { it.authentication }
            .map { it.name }
            .doOnNext {
                tracer.currentSpanCustomizer()?.tag("userId", it)
                tracer.createBaggage("userId", it)
            }
            .then(chain.filter(exchange))
    }
)
```

**Comment by marcingrzejszczak** [comment]
Have you defined that the `userId` should be flushable (https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage) ?

**Comment by Michal-Kucera** [comment]
Can you please be more specific? I'm not sure how I can use this functionality with excluded `org.springframework.cloud:spring-cloud-sleuth-brave` from `org.springframework.cloud:spring-cloud-starter-sleuth` dependency

**Comment by marcingrzejszczak** [comment]
I'm sorry I got super confused (I've forgotten that we're in Sleuth OTel project :facepalm: ). 

Can you please create a non Kotlin, Maven application that reproduces this issue? I will then look into that asap.

**Comment by Michal-Kucera** [comment]
Sure thing, I'll create one right away, thanks @marcingrzejszczak !

**Comment by Michal-Kucera** [comment]
Please check out https://github.com/Michal-Kucera/spring-cloud-sleuth-otel-webflux-baggage repo, there are two branches.

**FYI** I've noticed that in Java the `userId` doesn't appear in logs any more even in case as captured in the screenshot below - perhaps it's a different thread?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/46457233/185407367-a76c37fd-26cf-4993-a005-73c39a1e81bc.png">

**Comment by marcingrzejszczak** [comment]
You were missing this

```yaml
spring:
  sleuth:
    baggage:
      correlation-fields:
        - userId
```

in your configuration - check this https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/project-features.html#features-baggage for more details

**Comment by Michal-Kucera** [comment]
Oh right, sorry, have just fixed it, it was only a copy-paste issue in the test repo 🤕

Indeed, in this test repo it works for both - logging in **web filter**, as well as in **controller**, yet we are still in one thread only, which in my case is `reactor-http-nio-2` (I tested this a couple of times).

In my "real" code -- which is written in Kotlin + coroutines -- **web filter** runs in one thread (e.g. `parallel-5 thread`) and **controller** in another one (e.g. `reactor-http-epoll-6`). In this scenario logging of `userId` works only if the logger is triggered in the same thread as **web filter**.

Will try to simulate multiple threads in test repo with Java to see if this is related to Kotlin coroutines, or not..

**Comment by Michal-Kucera** [comment]
After some investigation I ended up with adding [io.github.numichi:reactive-logger](https://github.com/Numichi/reactive-logger) dependency, which is an upgrade of [kotlinx-coroutines-slf4j](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-slf4j) (as I understood). With this we can propagate MDC context between coroutines and reactor's threads.

The following snippets could be useful, if somebody wants to copy-paste my solution ->

# Web Filter
```kotlin
import io.github.numichi.reactive.logger.reactor.MDCContext.modifyContext
import org.springframework.boot.web.reactive.filter.OrderedWebFilter
import org.springframework.cloud.sleuth.Tracer
import org.springframework.context.annotation.Configuration
import org.springframework.security.config.web.server.SecurityWebFiltersOrder.AUTHENTICATION
import org.springframework.security.core.context.ReactiveSecurityContextHolder
import org.springframework.web.server.ServerWebExchange
import org.springframework.web.server.WebFilterChain
import reactor.core.publisher.Mono
import reactor.util.context.Context

@Configuration
class UserIdWebFilter(
    private val tracer: Tracer
) : OrderedWebFilter {

    companion object {
        const val USER_ID = "userId"
    }

    override fun getOrder() = AUTHENTICATION.order + 1

    override fun filter(
        exchange: ServerWebExchange,
        chain: WebFilterChain
    ): Mono<Void> = ReactiveSecurityContextHolder.getContext()
        .mapNotNull { it.authentication }
        .map { it.name }
        .doOnNext { createUserIdBaggage(it) }
        .doOnNext { addUserIdTag(it) }
        .flatMap { userId ->
            chain
                .filter(exchange)
                .contextWrite {
                    addUserIdToMdc(it, userId)
                }
        }

    private fun createUserIdBaggage(userId: String) = tracer.createBaggage(USER_ID, userId)

    private fun addUserIdTag(userId: String) = tracer.currentSpanCustomizer()?.tag(USER_ID, userId)

    private fun addUserIdToMdc(context: Context, userId: String) = modifyContext(context) { it[USER_ID] = userId }
}
```

# Extension for KLogger ([kotlin-logging](https://github.com/MicroUtils/kotlin-logging) library)
```kotlin
import io.github.numichi.reactive.logger.coroutine.readMdc
import mu.KLogger
import org.slf4j.MDC

suspend fun KLogger.withUserId(): KLogger {
    runCatching {
        readMdc()["userId"]
    }.onSuccess {
        MDC.put("userId", it)
    }.onFailure { e ->
        this.warn(e) { "Couldn't read userId from the reactive MDC context" }
    }
    return this
}
```

# Usage of withUserId extension (logs trace ID, span ID, as well as user ID)
```kotlin
import com.payxpert.account.extension.withUserId
import mu.KotlinLogging.logger
import org.springframework.stereotype.Component

private val logger = logger {}

@Component
class FooComponent {

  fun doSomething() = logger.withUserId().info { "hello world" }
}
```

P.S. Would be great if this could work out-of-the-box though :)
