### ISSUE TITLE
Docs: Broken link in Spring cloud sleuth otel documentation

### ISSUE THREAD

**Issue by santoshkashyap** [spring-projects-experimental/spring-cloud-sleuth-otel#133]
**Describe the bug**

In the documentation https://spring-projects-experimental.github.io/spring-cloud-sleuth-otel/docs/1.1.0/reference/html/using.html# there is a broken link "integrations available in Spring Cloud Sleuth OTel" (which refers to https://spring-projects-experimental.github.io/spring-cloud-sleuth-otel/docs/1.1.0/reference/html/integrations ). Please fix it. Thank you.

**Comment by paragniist** [comment]
Hi Team,
Can you please assign this issue on my name?
I would like to submit the PR.

**Comment by paragniist** [comment]
Hi @santoshkashyap 
Can you pls let me know, whether do we need to merge the fix back to the older version?
Regards
Parag

**Comment by jonatan-ivanov** [comment]
@paragniist Please see the milestone assigned to this issue. `1.1.x` means (at the moment) that this should be fixed on `main`.

**Comment by jonatan-ivanov** [comment]
Thank you!
Indeed, it seems this was fixed in #144 but the commit pointed to #113 instead of #133 (this).
