### ISSUE TITLE
Difference with spring-cloud-sleuth-brave

### ISSUE THREAD

**Issue by zhenchuan9r** [spring-projects-experimental/spring-cloud-sleuth-otel#134]
Sorry but I would like to ask what is the difference between this project and spring-cloud-sleuth-brave.
I'm using sleuth default tracing implementation which is brave.
I want to know how far will this project go and if it will replace brave in the future.
Thanks.

**Comment by marcingrzejszczak** [comment]
Spring Cloud Sleuth is feature complete and you should migrate to Micrometer Tracing and Boot 3 in the future. You can read the migration guide here https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide
