### ISSUE TITLE
Warning logs with Spring Cloud 21.0.5

### ISSUE THREAD

**Issue by RomainWilbert** [spring-projects-experimental/spring-cloud-sleuth-otel#145]
I know it is not officially supported, but while using Spring Cloud version 2021.0.5, I have warning logs at startup 

`22-12-21 15:54:00.954[0;39m [33mWARN [0;39m [36m[scheduling-1][0;39m [2m-[0;39m [34mo.s.c.s.c.ApplicationJsonMessageMarshallingConverter[0;39m [31m:[0;39m [2mFailed to evaluate Jackson serialization for type [class org.springframework.cloud.sleuth.autoconfig.otel.actuate.OtelOtlpFinishedSpanWriter]: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed on call to `getDeclaredMethods()` on class `org.springframework.cloud.sleuth.autoconfig.otel.actuate.OtelOtlpFinishedSpanWriter`, problem: (java.lang.NoClassDefFoundError) io/opentelemetry/proto/trace/v1/ResourceSpans[0;39m`

Your library depends on opentelemetry-proto and opentelemetry-exporter-otlp-common.

Class OtelOtlpFinishedSpanWriter uses following import for ResourceSpans : io.opentelemetry.proto.trace.v1.ResourceSpans; which comes from opentelemetry-proto. Package is different in opentelemetry-exporter-otlp-common (io.opentelemetry.proto.trace.v1.internal).

I don't get if both dependencies are necessary. I thought it should be one or another...but the different package issue becomes a blocker ? Is opentelemetry-proto mandatory ?

**Comment by marcingrzejszczak** [comment]
Most likely you have a problem with classpath, are you setting any dependencies' versions manually?
