### ISSUE TITLE
Support for AWS X-Ray 

### ISSUE THREAD

**Issue by sibethencourt** [spring-projects-experimental/spring-cloud-sleuth-otel#146]
**Is your feature request related to a problem? Please describe.**
X-Ray has its own collector implementation that requires a specific format for traceIds. Because of this, the otlp exporter is not able to transfer traces to X-Ray. This is the log error:

```
debug	awsxrayexporter@v0.66.0/awsxray.go:100	Error translating span.	{"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "invalid xray traceid: 970d7933a1b683da293e20e8047f2468"}
```

It is related to this bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2396

**Describe the solution you'd like**
Provide a way to define a custom traceId generator, AWS already offers one: [AwsXrayIdGenerator](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/b5d88e223c8c316b5d97474e5d2ff8fc4b428af1/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayIdGenerator.java)

I need support for custom Id generators: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#id-generators should allow us to fix the issue.

**Describe alternatives you've considered**
I tried to look up the code and see if I can find a way to override the Id generators, but I haven't been able to do it so far. Right now the alternatives are either replacing X-Ray or not using sleuth-otel.

**Additional context**
More context here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1646

Because the error I received and the comments in other forums it seems very clear what is the issue, but I haven't been able to confirm it yet, since I haven't found a way to workaround the problem.

**Comment by sibethencourt** [comment]
Managed to get it working but had to copy some code to override one of the beans:

I had to copy this function in my project and add the IdGenerator https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.java#L91

```
    @Bean
    fun otelTracerProvider(spanLimits: SpanLimits, spanProcessors: ObjectProvider<MutableList<SpanProcessor>>, spanExporterCustomizer: SpanExporterCustomizer, spanExporters: ObjectProvider<List<SpanExporter>>, sampler: Sampler, resource: Resource, spanProcessorProvider: SpanProcessorProvider): SdkTracerProvider {
        val sdkTracerProviderBuilder = SdkTracerProvider.builder().setResource(resource).setSampler(sampler).setSpanLimits(spanLimits)

        val processors = spanProcessors.getIfAvailable { mutableListOf() }

        processors.addAll(spanExporters.getIfAvailable { ArrayList() }.stream()
            .map { e -> spanProcessorProvider.toSpanProcessor(spanExporterCustomizer.customize(e)) }
            .collect(Collectors.toList()))

        processors.forEach(Consumer { spanProcessor: SpanProcessor? ->
            sdkTracerProviderBuilder.addSpanProcessor(
                spanProcessor!!
            )
        })
        return sdkTracerProviderBuilder
            .setIdGenerator(object : IdGenerator {
                override fun generateSpanId() = AwsXrayIdGenerator.getInstance().generateSpanId()
                override fun generateTraceId() = AwsXrayIdGenerator.getInstance().generateTraceId()
            })
            .build()
    }
```

**Comment by marcingrzejszczak** [comment]
Support was there but for the deprecated AWS XRay text maps. It's enough for you to pass the propagation type to be AWS. You can read more about this here https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/howto.html#how-to-change-context-propagation.

 With this commit https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/commit/4fc825b9998821155505b05ba43b35e7ddf4cc76 we're adding support for the contrib class from the `io.opentelemetry.contrib:opentelemetry-aws-xray-propagator` dependency

**Comment by JulianDoe** [comment]
It seems, that the bug is still out there. We used the [version 1.1.1](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/releases/tag/v1.1.1) which should fix it, but we run in the same problem as @sibethencourt. We used his workaround to overwirte the bean with the correct AwsXrayIdGenerator which also worked in our case.

We followed your comment @marcingrzejszczak and just pass the propagation type via the application.properties as the documentation describes it but nothing came through x-ray. Is there more to be configured to generate the correct aws ids?

**Comment by marcingrzejszczak** [comment]
Have you added the `io.opentelemetry.contrib:opentelemetry-aws-xray-propagator` dependency? If that's the case can you debug the `CompositeTextMapPropagator` class to see why AWS is not getting picked?

**Comment by JulianDoe** [comment]
Yes, I added `io.opentelemetry.contrib:opentelemetry-aws-xray-propagator` dependency to the project. The debug message is as follows
`
![grafik](https://user-images.githubusercontent.com/25430219/213425563-c5c0318b-ddf5-488e-b640-5eee960e7e5b.png)
`
However, I don't know why besides AWS the other propagators were found/added, but aws is there however the traces not coming through.
Our application config yml is as follows:
```
spring:
  mandatory-file-encoding: UTF-8
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false # prevents the issue in HELP-47285, printing dates in timestamps in our response json
  main:
    allow-circular-references: true
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1
      propagation:
        type: AWS
```

**Comment by marcingrzejszczak** [comment]
Can you actually try to put a debugger to the `CompositeTextMapPropagator` class to see why AWS is not getting picked?

**Comment by JulianDoe** [comment]
The debug showed that the AWS is as a type configured (see the debug variables in the screenshot) and the first AWS propagator will be selected for the mapping (also see screenshot). 
  
![grafik](https://user-images.githubusercontent.com/25430219/213444030-8dc56ce8-8093-43e4-9d1c-e3b69a7e840f.png)

**Comment by marcingrzejszczak** [comment]
So it looks that the `AwsXrayPropagator` should be properly picked. Have you created an `AwsXrayPropagator` as a bean and configured it so that it follows your requirements?

**Comment by epit787** [comment]
Hi, I try to take over today for my colleague as he is ill today.
Maybe I get this wrong, but the AwsXrayPropagator has nothing which could be configured. But I tried to add the propagator as bean:
```
@Bean
public AwsXrayPropagator awsXrayPropagator() {
    return AwsXrayPropagator.getInstance();
}
```
But also with no effect. Can you elaborate on how to configure the AwsXrayPropagator?
Thank you in advance
