### ISSUE TITLE
OtelHttpServerHandler.class and SamplerFunction<HttpRequest>

### ISSUE THREAD

**Issue by hyunbeeds** [spring-projects-experimental/spring-cloud-sleuth-otel#160]
**Is your feature request related to a problem? Please describe.**

I want to only trace request using method POST, DELETE.

In the OtelHttpClientHandler and brave, I can easily use SamplerFunction<HttpRequest> to achieve this, but I can't use that way in the OtelHttpServerHandler.. I can use only skip patterns to filter ServerRequest..

```
@Override
	public Span handleReceive(HttpServerRequest request) {
		String url = request.path();
		boolean shouldSkip = !StringUtils.isEmpty(url) && this.pattern.matcher(url).matches();
		if (shouldSkip) {
			return OtelSpan.fromOtel(io.opentelemetry.api.trace.Span.getInvalid());
		}
		Context parentContext = Context.current();
		if (instrumenter.shouldStart(parentContext, request)) {
			Context context = instrumenter.start(parentContext, request);
			return span(context, request);
		}
		else {
			return OtelSpan.fromOtel(io.opentelemetry.api.trace.Span.getInvalid());
		}
	}
```

**Describe the solution you'd like**
add SamplerFunction<HttpRequest> in OtelHttpServerHandler constructor and use Qualifier might seem to achieve this..

**Comment by marcingrzejszczak** [comment]
Sleuth and Sleuth OTel are feature complete projects and this looks like a new feature. Unless you're willing to contribute it we would not be planning on adding it.
