### ISSUE TITLE
Upgrade OTel to 1.24.0

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects-experimental/spring-cloud-sleuth-otel#161]

**Comment by singhanuj1393** [comment]
Hi marcingrzejszczak,

It does not support in reactive webflux application.

Getting trace id and span id 00000000000000.

**Comment by singhanuj1393** [comment]
Hi @marcingrzejszczak 

In this, there is an issue with reactive application(webflux).

Getting invalid traces in logs.

DEBUG [webfluxapp,00000000000000000000000000000000,0000000000000000] 68848 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [26c4e0a6-2] Completed 200 OK
DEBUG [webfluxapp,00000000000000000000000000000000,0000000000000000] 68848 --- [ctor-http-nio-2] r.n.http.server.HttpServerOperations     : [26c4e0a6-2, L:/127.0.0.1:8090 - R:/127.0.0.1:2040] Last HTTP response frame
