### ISSUE TITLE
Why exclude Brave from sleuth?

### ISSUE THREAD

**Issue by cjl111** [spring-projects-experimental/spring-cloud-sleuth-otel#162]
Sleuth3.x.x only adds traceId and spanId to the MDC
![image](https://user-images.githubusercontent.com/38237837/226234253-1b513cb8-47cb-4c46-a47c-cecf5e37f91b.png)

But I want to add parentId to my log
So I extended the CorrelationScopeCustomizer in the project
![image](https://user-images.githubusercontent.com/38237837/226234605-b88669b6-3b7b-408e-926e-6789e864a9c8.png)

However, due to the need to exclude the sleuth-otel, after adding the exclude Brave
At this point, the dependency cannot be found
![image](https://user-images.githubusercontent.com/38237837/226235037-02d51fd2-1164-4f13-b0e3-9522fce05cb2.png)

**Comment by jonatan-ivanov** [comment]
You need to decide if you want to use Brave or OTel, if you use the default starter, you should have Brave but in that case you should not use OTel.
