### ISSUE TITLE
feature request for `span.kind` exclude 

### ISSUE THREAD

**Issue by KamJohn** [spring-projects-experimental/spring-cloud-sleuth-otel#165]
** I cant config my sleuth-otel to tracing on just case for span.kind equals to client **
In a tracing route,there`s half of traces are not my wants,because there is allways a  almost same client span to a server span in a same request. these client kind span marked with the red square in the paste img:

![image](https://user-images.githubusercontent.com/33511022/229508456-34be81f7-a482-4d48-b1b9-69ccf0509f3b.png)

so how can i config my application.yaml in a property or in some way else to resove it, please help

**Comment by marcingrzejszczak** [comment]
Spring Cloud Sleuth OTel is in maintance mode - we don't want to add any new features. We suggest migrating to Micrometer Tracing (https://micrometer.io/docs/tracing).
