### ISSUE TITLE
Issues with using otelBatchSpanProcessorProvider

### ISSUE THREAD

**Issue by hyunbeeds** [spring-projects-experimental/spring-cloud-sleuth-otel#166]
**Is your feature request related to a problem? Please describe.**

I'm using spring boot 2.7.9 / spring.cloud 2021.0.6 / spring.dependency-management 1.0.15.RELEASE
and in order to use spring-cloud-sleuth-otel I added below implementations.

```
    implementation('org.springframework.cloud:spring-cloud-starter-sleuth') {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-sleuth-brave'
    }
    implementation('org.springframework.cloud:spring-cloud-sleuth-otel-autoconfigure')
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.6"
        mavenBom "org.springframework.cloud:spring-cloud-sleuth-otel-dependencies:1.1.0"
    }
}
```
-> and this configured results in opentelemetry to version 1.18.0 

To use otelBatchSpanProcessorProvider we need class "io.opentelemetry.api.metrics.GlobalMeterProvider"
so I added below implementation and it seems to be working. (https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/4e82d2579294ae91d03891ac85e783afb0219323/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.java#L105)

```
implementation 'io.opentelemetry:opentelemetry-api-metrics:1.10.0-alpha-rc.1'
```

It seems that GlobalMeterProvider deprecated in opentelemetry..

Am I using in a right way to use otelBatchSpanProcessorProvider or could I add property about choosing otelBatchSpanProcessorProvider or SimpleSpanProcessor?
(ex. spring.sleuth.otel.processor.batch.enabled )

**Comment by marcingrzejszczak** [comment]
Can you use the latest 1.1.3 version of Sleuth OTel and see if you have any issues?

**Comment by hyunbeeds** [comment]
It seems okay when I use otel-dependencies version 1.1.3 and io.opentelemetry:opentelemetry-api-metrics:1.10.0-alpha-rc.1

but is this the recommended way to use batchOtelProcessor?..

**Comment by marcingrzejszczak** [comment]
I don't know you should talk to the otel team about this I guess.
