### ISSUE TITLE
Option to Use http/protobuf instead of gRPC.

### ISSUE THREAD

**Issue by NicolaeV** [spring-projects-experimental/spring-cloud-sleuth-otel#170]
Greetings, We are using DynaTrace for our distributed tracing/metrics/logs and it seems there is no support for gRPC from DynaTrace. 

see: https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/getting-started/otlp-export#otlp-details
and the **_entirety_** of a related log:
`WARN  i.o.e.i.grpc.OkHttpGrpcExporter - Failed to export spans. Server responded with HTTP status code 200. Error message: `

I'd like it if there was an easily configurable protocol property for the exporter, perhaps an application.properties entry such as:

`otel.exporter.otlp.protocol` 

see: https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpConfigUtil.java#L45C1-L45C1

I'm considering doing all the configuration manually instead of relying on the autoconfiguration, but I'm not sure where to start, can anybody point me in the right direction for manual configuration?

Thank you for reading my issue, I hope you'll be patient with me! :)

**Comment by marcingrzejszczak** [comment]
Thanks for filing the issue @NicolaeV ! 

Spring Cloud Sleuth is a deprecated project - so is Spring Cloud Sleuth OTel. We're not considering to add any new features to it. Please migrate to Micrometer Tracing https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide

**Comment by NicolaeV** [comment]
Unfortunately I cannot upgrade past Spring boot 2.7 for the time being. I understand this is deprecated and no new features will be added, but do you know of any way to override and use an http/protobuf exporter?

Or could you point me to any resource (maybe where in the source code here) that can help me do the autoconfiguration manually?

Thank you for taking the time to respond to my issue,
Happy Holidays!

**Comment by marcingrzejszczak** [comment]
You can create your own exporter bean, that should be sufficient. Have you tried it out?

**Comment by marcingrzejszczak** [comment]
No problem, glad that you sorted things out! Happy holidays to you too!
