### ISSUE TITLE
Spring-Sleuth does not process have all instrumentation done by Java Agent in particular  @WithSpan annotation

### ISSUE THREAD

**Issue by bmistry13** [spring-projects-experimental/spring-cloud-sleuth-otel#53]
**Is your feature request related to a problem? Please describe.**
Spring-Sleuth does not process have all instrumentation done by Java Agent in particular  @WithSpan annotation.
So many of library e.g Spring-Data, Hibernate so we can even see SQL queries.  There are lots of gaps between Java Agent and Spring Sleuth.  I would appreciate if you can look into it.

**Describe the solution you'd like**

Today, we use Spring-Sleuth for auto instrumentation, and the same code is run with Java Agent we can Spring-Data and Hibernate SQL logs span and actual SQL as well.  

**Describe alternatives you've considered**

My alternate was to use Java Agent with Spring-Sleuth and it works, but the issue is tracing logs does not work. Somehow it stopped working after the latest Spring-Sleuth version of the snapshot.  There is no guarantee that interoperability between the two will work. so it is best if Spring-Sleuth supports all libs that are supported by Java Agent for auto instrumentation.

**Additional context**

**Comment by marcingrzejszczak** [comment]
>  So many of library e.g Spring-Data, Hibernate so we can even see SQL queries. There are lots of gaps between Java Agent and Spring Sleuth. I would appreciate if you can look into it.

Please file separate issues under spring-cloud/spring-cloud-sleuth` with missing instrumentations

**Comment by bmistry13** [comment]
> Please file separate issues under spring-cloud/spring-cloud-sleuth` with missing instrumentations

Please review https://github.com/spring-cloud/spring-cloud-sleuth/issues/1951

**Comment by jonatan-ivanov** [comment]
Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline. We encourage to migrate to Micrometer Tracing.
