### ISSUE TITLE
Autoconfiguration for Lettuce OTel instrumentation

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects-experimental/spring-cloud-sleuth-otel#67]
**Is your feature request related to a problem? Please describe.**
Spring Cloud Sleuth OTel doesn't provide instrumentation for Lettuce.

**Describe the solution you'd like**
The OpenTelemetry project provides a library to instrument [Lettuce](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/lettuce/lettuce-5.1/library). We could add auto-configuration for it in Sleuth OTel similarly to how Lettuce instrumentation has been configured for Brave in Sleuth.

**Additional context**
See https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/issues/66

**Comment by marcingrzejszczak** [comment]
The best way would be to go to Sleuth and rewrite https://github.com/spring-cloud/spring-cloud-sleuth/blob/602749a8d148c281e9f519a1ef362744eeff1f44/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/redis/TraceLettuceClientResourcesBuilderCustomizer.java#L31 to not use BraveTracing but an implementation that uses Sleuth's API. I had it on my radar but didn't have time to do it. In short - we'd need to basically copy paste what is done there in Lettuce with Brave and convert it to use Sleuth's API. Once we have that we can register that implementation and then redirect to either Brave or OTel.

**Comment by ThomasVitale** [comment]
@marcingrzejszczak Perfect! Thanks for your comment. I'll open an issue on the Sleuth project then and go back to this one later.

**Comment by marcingrzejszczak** [comment]
With the PR merged you can continue work on this one. I've started a branch but there's a lot more work to be done there - you can check it out here https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/tree/otel_lettuce

**Comment by ThomasVitale** [comment]
Thank you @marcingrzejszczak, I'll have a look

**Comment by klubi** [comment]
Hi.
Any chance lettuce support will make it into this library anytime soon?
Thanks!

**Comment by marcingrzejszczak** [comment]
@ThomasVitale did you have any time to look into this? :grimacing:

**Comment by marcingrzejszczak** [comment]
Sleuth OTel is feature complete. We suggest migration to Micrometer Tracing - https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide
