### ISSUE TITLE
Update tests for Spring Cloud Stream Reactive

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-projects-experimental/spring-cloud-sleuth-otel#84]
https://github.com/spring-cloud/spring-cloud-sleuth/commit/90417f1f074f41fed7b3bfb8e0c8c4e5a6274dd8

**Comment by jonatan-ivanov** [comment]
Sleuth reached the [end of its OSS support](https://spring.io/projects/spring-cloud-sleuth#support) timeline. We encourage to migrate to Micrometer Tracing.
