### ISSUE TITLE
Documentation bugs

### ISSUE THREAD

**Issue by thombergs** [spring-projects-experimental/spring-cloud-sleuth-otel#92]
Some small "bugs" in the docs:

* "As the tracer implementation we’ll use OpenZipkin Brave." when it should say something like "we'll use the OpenTelemetry SDK" or similar.
* The `pom.xml` should contain a `<properties>` section like
  ```
    <properties>
        <release.train.version>2020.0.4</release.train.version>
        <spring-cloud-sleuth-otel.version>1.0.0-M3</spring-cloud-sleuth-otel.version>
    </properties>
  ``` 
  otherwise when I copy the `pom.xml` into my project, it complains about missing properties

**Comment by jonatan-ivanov** [comment]
@thombergs Thanks for reporting, I fixed the Brave vs. OTel issue. Not having properties in the pom I think is intentional so that it's easy version-independent configuration in the docs. You can add a properties section as you did or set the version in the version tag.
