### ISSUE TITLE
Link to Gitter is broken

### ISSUE THREAD

**Issue by dekobon** [spring-projects-experimental/spring-cloud-sleuth-otel#98]
**Describe the bug**
Documentation within the ["Getting Help" section](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/a05ae1e7fdc8d607f1f0ad14e32dddcc4b4b19b4/docs/src/main/asciidoc/documentation-overview.adoc) contains the line: "Chat with us at Spring Cloud Sleuth OTel Gitter". However, the link to gitter `http://https//gitter.im/spring-cloud/spring-cloud-sleuth-otel` is broken. Moreover, if you manually fix the link, it does not take you to a functioning gitter chat.

I'd to be able to engage with the developers on this project aside from filing bugs. Could a viable alternative to gitter be enabling github Discussions?

**Comment by dekobon** [comment]
Well, I just found the gitter link on the README badge. Link in docs is still broken. I'll work with my company's legal department and see if I can make it through the CLA to do a PR.

**Comment by marcingrzejszczak** [comment]
Perfect, we'd love to have your contributions!
