### ISSUE TITLE
Timeline and project explanations

### ISSUE THREAD

**Issue by migroskub** [spring-projects-experimental/spring-cloud-sleuth-otel#99]
Hey. I'd really like to use a Spring Boot & Project Reactor-based application with `otel`. I've seen that there is support for both [Spring Boot](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/README.md) and both for [Reactor](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/reactor/reactor-3.1/README.md). 

I'd like to know what is currently the most recommended way of doing so. Is this project still experimental and in early stages (and if so, is there any timeline for this super anticipated project to get out of the early stages??), and native use of the `otel` is more recommended, or would you already encourage people to use `spring-cloud-sleuth-otel`?

**Comment by jonatan-ivanov** [comment]
@migroskub The timeline of this project mostly affected by OTel.
OTel Tracing is not fully stable yet: `otel-instrumentation` is not stable, so this project can't be stable either. Please see this comment: https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/56#issuecomment-848944920.
Also check Maven Central, [`opentelemetry-instrumentation-api`](https://search.maven.org/search?q=g:io.opentelemetry.instrumentation%20AND%20a:opentelemetry-instrumentation-api) is in alpha.

I _guess_ the biggest roadblock in front of OTel tracing right now is having a stable release of the Semantic Conventions (the Semantic Conventions specification is experimental right now).

With these in mind, we do not recommend using `spring-cloud-sleuth-otel` at the moment in production (please check the OTel release notes, the releases usually contain breaking changes) but please feel free to experiment with the project and give feedback to us.

At the moment we recommend using Spring Cloud Sleuth without `spring-cloud-sleuth-otel`. Sleuth has its own API that abstracts away the tracing libraries so you can change them under the hood. By default, it uses [Brave](https://github.com/openzipkin/brave) as the tracing library (production-ready).

After OTel releases a stable version, we can release a stable version of `spring-cloud-sleuth-otel` too so we should be able recommend more options for you in prod in the future.

**Comment by migroskub** [comment]
Awesome. Thank you very much! If I will @jonatan-ivanov, I have one more question. This project will allow me in the future to replace Brave with any of the supported OTLP exporter integrations (For example [Elastic APM](https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html))?

**Comment by jonatan-ivanov** [comment]
Yes, here are your options:
1. Use Brave and something that supports the Zipkin format
2. Use Brave and implement your own "exporter" (or get a third-party one)
3. Use OTel and use something that supports OTLP or the format that an OTel "exporter" can emit
4. Use OTel and implement your own "exporter" (or get a third-party one)
5. Implement Sleuth's API (to support another Tracing library)

1 and 2 are recommended in prod usage (you can do 5 too but it's a lot of work).
1 and 3 are out of the box options and as far as I remember Elastic APM supports both Zipkin and OTLP so you should be able to switch between them.

**Comment by migroskub** [comment]
I see. Thank you! By saying "Zipkin format", do you mean OpenTracing? I can't figure out whether Elastic APM really supports the Zipkin format. I've only seen [this one](https://www.elastic.co/blog/distributed-tracing-opentracing-and-elastic-apm). 

Plus I can't figure out what shall I do to make it work. Do I need an [Elastic APM server](https://github.com/elastic/apm-server), and also a Zipkin Server? Or that option 1 should allow me to use Brave with an Elastic APM server directly

**Comment by jonatan-ivanov** [comment]
No, by saying the Zipkin format, I meant the [Zipkin format](https://zipkin.io/pages/data_model.html). :) I'm not sure how OpenTracing comes here but please keep in mind that OpenTracing never went GA and it is already deprecated.

I guess you need to decide if you want to use Elastic **or** Zipkin. Sleuth will not know which one are you using, the only thing it cares about is the API, if elastic fully supports that, it will work out of the box.
This is from the [Elastic docs](https://www.elastic.co/blog/distributed-tracing-opentracing-and-elastic-apm):
>Not surprisingly, Elasticsearch has been used as the backend data store for other tracers like Zipkin and Jaeger, due to its massive scalability and rich analytics capabilities. Shipping Zipkin or Jaeger tracing data into Elasticsearch is a simple configuration for both of them. Once the tracing data is inside Elasticsearch, you can use the powerful analytic and visualization capability of Kibana to analyze your tracing information and create eye-catching visualizations that provide deep insight into your application performance.

If you have questions around this, I would rather ask Elastic about this, I haven't tried this with ElasticAPM.

**Comment by migroskub** [comment]
Thanks a lot. From the Spring Cloud Sleuth side, you wouldn't want do add more details in the document about this possibility? That is quite advanced to understand that this is really an option, and I think that a basic explanation in the docs might help others too.
